name: DBT Build

on:
  push:
    branches:
      - main #
  pull_request:
    types: [closed, opened, synchronize]  # 👈 Add this trigger for PR closures      


jobs:
  run-dbt:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          submodules: true
  

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Write BIGQUERY_KEYFILE_JSON to File
        env:
          BIGQUERY_KEYFILE_JSON_BASE64: ${{ secrets.BIGQUERY_KEYFILE_JSON_BASE64 }}
        run: |
          mkdir -p ./cne-dbt-template/.keys
          echo "$BIGQUERY_KEYFILE_JSON_BASE64" | base64 --decode > ./cne-dbt-template/.keys/staging.json
          echo "BIGQUERY_KEYFILE_PATH=./cne-dbt-template/.keys/staging.json" >> $GITHUB_ENV
  
      - name: Build Docker image
        run: |
          ls -la
          ls -la  cne-dbt-template
          docker build -t ghcr.io/${{ github.repository }}/dagster_dbt:latest .
    
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/dagster_dbt:latest
    